<?php
declare(strict_types=1);
/**
 *  This file is part of the AI Pic Repository Page Component plugin for ILIAS, which allows
 *  users of your platform to add an image component to their pages, generated by an external AI model.
 *  This plugin is created and maintained by SURLABS.
 *
 *  The AI Pic Repository Page Component plugin for ILIAS is open-source and licensed under GPL-3.0.
 *  For license details, visit https://www.gnu.org/licenses/gpl-3.0.en.html.
 *
 *  To report bugs or participate in discussions, visit the Mantis system and filter by
 *  the category "AI Pic" at https://mantis.ilias.de.
 *
 *  More information and source code are available at:
 *  https://github.com/surlabs/AIPicForILIAS
 *
 *  If you need support, please contact the maintainer of this software at:
 *  info@surlabs.com
 *
 */

namespace db;

use exceptions\AIPicException;
use interfaces\BasicDbChildInterface;

/**
 * class AIPicDatabase
 * @authors Sergio Santiago, Abraham Morales <info@surlabs.com>
 */

class AIPicDatabase extends BasicDb implements BasicDbChildInterface {
    const ALLOWED_TABLES = [
        'aip_config'
    ];
    public function __construct() {

        parent::__construct(self::ALLOWED_TABLES);
    }

    public function throwException(string $message): void {
        throw new AIPicException($message);
    }

    /**
     * @throws \Exception
     */
    public function getConfig(): array {
        return $this->select('aip_config', null, null);
    }

}