<?php
declare(strict_types=1);
/**
 *  This file is part of the AI Pic Repository Page Component plugin for ILIAS, which allows
 *  users of your platform to add an image component to their pages, generated by an external AI model.
 *  This plugin is created and maintained by SURLABS.
 *
 *  The AI Pic Repository Page Component plugin for ILIAS is open-source and licensed under GPL-3.0.
 *  For license details, visit https://www.gnu.org/licenses/gpl-3.0.en.html.
 *
 *  To report bugs or participate in discussions, visit the Mantis system and filter by
 *  the category "AI Pic" at https://mantis.ilias.de.
 *
 *  More information and source code are available at:
 *  https://github.com/surlabs/AIPicForILIAS
 *
 *  If you need support, please contact the maintainer of this software at:
 *  info@surlabs.com
 *
 */

use ILIAS\COPage\Editor\Server\UIWrapper;
use ILIAS\UI\Component\Input\Container\Form\Standard;
use JetBrains\PhpStorm\NoReturn;

class ilAIPicEditorGUI
{
    protected ilTemplate $template;
    private ilPageComponentPlugin $plugin;
    private AIPicRequestInterface $AIPicProvider;
    private UploadServiceAIPicGUI $uploader;

    private string $placeHolderUrl = "./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/images/placeholder.png";

    public function __construct(ilPageComponentPlugin $plugin, AIPicRequestInterface $AIPicProvider)
    {
        $this->plugin = $plugin;
        $this->AIPicProvider = $AIPicProvider;
        $this->uploader = new UploadServiceAIPicGUI();
    }

    public function getEditorElements(UIWrapper $ui_wrapper, string $page_type, \ilPageObjectGUI $page_gui, int $style_id): array
    {
        global $DIC;
        $lng = $DIC->language();

        return [
            "icon" => $ui_wrapper->getRenderedIcon("xaimg"),
            "title" => $lng->txt("image_generator")
        ];
    }

    public function getEditComponentForm(UIWrapper $ui_wrapper, string $page_type, \ilPageObjectGUI $page_gui, int $style_id, string $pcid): string
    {
        global $DIC;

        $ui = $DIC->ui()->factory();
        $renderer = $DIC->ui()->renderer();

        $form = $renderer->render($this->getPromptForm());
        $image = $ui->image()->responsive(
            "https://ssantiago.ilias9.com/src/UI/examples/Image/HeaderIconLarge.svg",
            "Thumbnail Example"
        );

        return $form . $renderer->render($image);
    }

    public function getPromptForm(): Standard
    {
        global $DIC;

        $ui = $DIC->ui()->factory();
        $lng = $DIC->language();

        // 1. Campos originales para la generación de la IA
        $file = $ui->input()->field()->file($this->uploader, "")->withAcceptedMimeTypes(['image/jpeg', 'image/jpg', 'image/png', 'image/gif']);

        $styles_options = [
            "realistic" => $this->plugin->txt("style_realistic"),
            "artistic" => $this->plugin->txt("style_artistic"),
            "minimal" => $this->plugin->txt("style_minimal"),
            "anime" => $this->plugin->txt("style_anime"),
            "vintage" => $this->plugin->txt("style_vintage"),
            "cartoon" => $this->plugin->txt("style_cartoon"),
        ];
        $selecStyle = $ui->input()->field()->select($this->plugin->txt("select_style"), $styles_options, $this->plugin->txt("select_style_image"))->withRequired(false);
        $widthInput = $ui->input()->field()->numeric($this->plugin->txt("width"), $this->plugin->txt("width_px"))->withRequired(true)->withValue(50);
        $prompt = $ui->input()->field()->textarea($this->plugin->txt("prompt"), $this->plugin->txt("prompt_description"))->withRequired(true);

        // 2. Native Media Object properties
        $title = $ui->input()->field()->text("Title"); // Opcional: cambiar por $this->plugin->txt("title") en el futuro

        $style_classes = [
            "MediaContainer" => "MediaContainer",
            "MediaContainerFull100" => "MediaContainerFull100",
            "MediaContainerHighlighted" => "MediaContainerHighlighted",
            "MediaContainerMax50" => "MediaContainerMax50",
            "MediaContainerSeparated" => "MediaContainerSeparated"
        ];
        $styleClass = $ui->input()->field()->select("Style Class", $style_classes)->withValue("MediaContainer");

        $alignments = [
            "Center" => "Center",
            "Left" => "Left",
            "Right" => "Right",
            "LeftFloat" => "Left, Floating",
            "RightFloat" => "Right, Floating"
        ];
        $selectAligment = $ui->input()->field()->select("Alignment", $alignments)->withValue("Center")->withRequired(true);

        $showFullscreen = $ui->input()->field()->checkbox("Show Fullscreen");
        $textRepresentation = $ui->input()->field()->text("Text Representation")->withByline("Used for image 'alt' attribute.");

        // 3. Group fields in section
        $fields = [
            "prompt" => $prompt,
            "file" => $file,
            "styles" => $selecStyle,
            "widthInput" => $widthInput,
            "title" => $title,
            "styleClass" => $styleClass,
            "aligments" => $selectAligment,
            "showFullscreen" => $showFullscreen,
            "textRepresentation" => $textRepresentation
        ];

        $section1 = $ui->input()->field()->section($fields, $this->plugin->txt("configuration"));

        $DIC->ctrl()->setParameterByClass('ilAIPicPluginGUI', 'methodDesired', 'saveImage');
        $form_action = $DIC->ctrl()->getLinkTargetByClass('ilAIPicPluginGUI', "insert");

        return $ui->input()->container()->form()->standard($form_action, [$section1])->withSubmitLabel($lng->txt("send"))->withDedicatedName("AIPicForm");
    }

    public function getPromptFormWithProperties(array $properties): Standard
    {
        global $DIC;
        $ui = $DIC->ui()->factory();
        $lng = $DIC->language();

        // 1. AI generation fields with recovered values
        $prompt = $ui->input()->field()->textarea($this->plugin->txt("prompt"), $this->plugin->txt("prompt_description"))->withValue($properties["prompt"] ?? "")->withRequired(true);
        $file = $ui->input()->field()->file($this->uploader, "")->withAcceptedMimeTypes(['image/jpeg', 'image/jpg', 'image/png', 'image/gif']);

        $styles_options = [
            "realistic" => $this->plugin->txt("style_realistic"),
            "artistic" => $this->plugin->txt("style_artistic"),
            "minimal" => $this->plugin->txt("style_minimal"),
            "anime" => $this->plugin->txt("style_anime"),
            "vintage" => $this->plugin->txt("style_vintage"),
            "cartoon" => $this->plugin->txt("style_cartoon"),
        ];
        $selecStyle = $ui->input()->field()->select($this->plugin->txt("select_style"), $styles_options, $this->plugin->txt("select_style_image"))->withValue($properties["styles"] ?? "realistic")->withRequired(false);
        $widthInput = $ui->input()->field()->numeric($this->plugin->txt("width"), $this->plugin->txt("width_px"))->withRequired(true)->withValue($properties["widthInput"] ?? 50);

        // 2. Native Media Object properties with recovered values
        $title = $ui->input()->field()->text("Title")->withValue($properties["title"] ?? "");

        $style_classes = [
            "MediaContainer" => "MediaContainer",
            "MediaContainerFull100" => "MediaContainerFull100",
            "MediaContainerHighlighted" => "MediaContainerHighlighted",
            "MediaContainerMax50" => "MediaContainerMax50",
            "MediaContainerSeparated" => "MediaContainerSeparated"
        ];
        $styleClass = $ui->input()->field()->select("Style Class", $style_classes)->withValue($properties["styleClass"] ?? "MediaContainer");

        $alignments = [
            "Center" => "Center",
            "Left" => "Left",
            "Right" => "Right",
            "LeftFloat" => "Left, Floating",
            "RightFloat" => "Right, Floating"
        ];
        $selectAligment = $ui->input()->field()->select("Alignment", $alignments)->withValue($properties["aligments"] ?? "Center")->withRequired(true);

        $showFullscreenValue = isset($properties["showFullscreen"]) && $properties["showFullscreen"] == 1;
        $showFullscreen = $ui->input()->field()->checkbox("Show Fullscreen")->withValue($showFullscreenValue);

        $textRepresentation = $ui->input()->field()->text("Text Representation")->withByline("Used for image 'alt' attribute.")->withValue($properties["textRepresentation"] ?? "");

        // 3. Group fields
        $fields = [
            "prompt" => $prompt,
            "file" => $file,
            "styles" => $selecStyle,
            "widthInput" => $widthInput,
            "title" => $title,
            "styleClass" => $styleClass,
            "aligments" => $selectAligment,
            "showFullscreen" => $showFullscreen,
            "textRepresentation" => $textRepresentation
        ];

        $section1 = $ui->input()->field()->section($fields, $this->plugin->txt("configuration"));

        $DIC->ctrl()->setParameterByClass('ilAIPicPluginGUI', 'methodDesired', 'saveImage');
        $form_action = $DIC->ctrl()->getLinkTargetByClass('ilAIPicPluginGUI', "update");

        return $ui->input()->container()->form()->standard($form_action, [$section1])->withSubmitLabel($lng->txt("send"))->withDedicatedName("AIPicForm");
    }

    public function renderForm(Standard $form): string
    {
        global $DIC;

        $refinery = $DIC->refinery();
        $renderer = $DIC->ui()->renderer();
        $request = $DIC->http()->request();
        $query = $DIC->http()->wrapper()->query();

        // Retrieve method flag from JS
        $methodDesired = "";
        if ($query->has("methodDesired")) {
            $methodDesired = $query->retrieve("methodDesired", $refinery->to()->string());
        }

        // Only intercept if sendPrompt flag is present to avoid overriding native submit
        if ($request->getMethod() == "POST" && $methodDesired === "sendPrompt") {
            $this->sendPromptByJs();
        }

        return $renderer->render($form);
    }

    public function generateImage(?string $url = null): string
    {
        global $DIC, $ilCtrl;

        $url = $url ?? $this->placeHolderUrl;
        $ui = $DIC->ui()->factory();
        $renderer = $DIC->ui()->renderer();
        $image = $ui->image()->responsive($url, "Generated_image");

        $urlButtonDownload = $ilCtrl->getLinkTargetByClass("ilAIPicPluginGUI", "insert");
        $buttonDownload = $ui->button()->standard($this->plugin->txt("button_download"), "#")->withOnLoadCode(function ($id) use ($urlButtonDownload) {
            return "$(\"#$id\").click(function() { callSaveEndpoint(\"$urlButtonDownload\"); });";
        });

        $ilCtrl->setParameterByClass('ilAIPicPluginGUI', 'methodDesired', 'sendPrompt');
        $urlButtonPrompt = $ilCtrl->getLinkTargetByClass("ilAIPicPluginGUI", "insert");
        $urlBase = $DIC->ctrl()->getLinkTargetByClass('ilAIPicPluginGUI', 'insert');

        $buttonGenerateImage = $ui->button()->standard($this->plugin->txt("generate_image"), "#")->withOnLoadCode(function ($id) use ($urlButtonPrompt, $urlBase) {
            return "$(\"#$id\").click(function(e) { e.preventDefault(); resendForm(\"$urlButtonPrompt\", \"$urlBase\"); });";
        });

        $buttonDownloadHtml = '<div id="downloadButton" style="display: none; margin-bottom: 10px; margin-top: 10px;">' . $renderer->render($buttonDownload) . '</div>';

        return '<div style="display: flex; align-items: center; flex-direction: column; justify-content: center; width: 100%;">' .
            '<div class="aipic-align-group" style="display: flex; flex-direction: column; align-items: center;">' .
            '<div id="imageDiv" style="padding: 10px; position: relative; display: flex; width: 100%; justify-content: center;">' .
            '<div id="loadingSpinner" style="display: none; position: absolute; background-color: white; box-shadow: 0 0 5px 2px #d1d1d1; top: 50%; left: 50%; transform: translate(-50%, -50%);">' .
            '<img src="./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/images/loading.gif" alt="loading""/>'
            . '</div>' .
            $renderer->render($image) .
            '</div>' .
            $buttonDownloadHtml .
            '<div id="redirectButton" style="margin: 10px auto;"' .
            ' data-txt-generate="' . htmlspecialchars($this->plugin->txt("generate_image")) . '"' .
            ' data-txt-generating="' . htmlspecialchars($this->plugin->txt("generating_image")) . '"' .
            ' data-txt-error-admin="' . htmlspecialchars($this->plugin->txt("err_contact_admin")) . '">' .
            $renderer->render($buttonGenerateImage) .
            '</div>' .
            '</div>' .
            '</div>';
    }

    public function manageDownloadImage(): void
    {
        global $DIC;

        $refinery = $DIC->refinery();
        $request = $DIC->http()->request();
        $query = $DIC->http()->wrapper()->query();

        $actionFinal = "";
        if ($query->has("methodDesired")) {
            $actionFinal = $query->retrieve("methodDesired", $refinery->to()->string());
        }

        if ($request->getMethod() == "GET" && $actionFinal == "downloadImage" && $query->has("urlDownload")) {
            $destiny = urldecode($query->retrieve("urlDownload", $refinery->to()->string()));

            $imagen = @file_get_contents($destiny);
            if ($imagen === false) {
                http_response_code(404);
                exit();
            }

            $query_string = parse_url($destiny, PHP_URL_QUERY);
            $params = [];
            if ($query_string !== null) {
                parse_str($query_string, $params);
            }

            $extension = pathinfo(parse_url($destiny, PHP_URL_PATH), PATHINFO_EXTENSION) ?: 'png';
            $content_type = $params['rsct'] ?? 'image/' . $extension;
            $fileName = "AIPic_" . date('Y-m-d_H-i-s') . ".$extension";

            header('Content-Description: File Transfer');
            header("Content-Type: $content_type");
            header('Content-Disposition: attachment; filename="' . $fileName . '"');
            header('Expires: 0');
            header('Cache-Control: must-revalidate');
            header('Pragma: public');
            header('Content-Length: ' . strlen($imagen));

            echo $imagen;
            exit();
        }
    }

    #[NoReturn]
    public function sendPromptByJs($httpCode = 200): void
    {
        set_time_limit(120);

        http_response_code($httpCode);
        header('Content-type: application/json');

        $rawPrompt = $_POST["prompt"] ?? "";
        $success = $this->AIPicProvider->sendPrompt($rawPrompt);

        if ($success) {
            $res = method_exists($this->AIPicProvider, 'getImagesPayloadArray')
                ? $this->AIPicProvider->getImagesPayloadArray()
                : [];

            if (!empty($res)) {
                echo json_encode(["image" => end($res)]);
                exit();
            }
        }

        $rawAiResponse = $this->AIPicProvider->getResponse();
        $decodedResponse = json_decode($rawAiResponse, true);

        if (is_array($decodedResponse) && ($decodedResponse['error'] ?? false) === true) {
            $langKey = $decodedResponse['error_key'] ?? 'no_images_found';
            $decodedResponse['message'] = $this->plugin->txt($langKey);

            echo json_encode($decodedResponse);
            exit();
        }

        echo json_encode([
            "Error" => $this->plugin->txt("no_images_found"),
            "Motivo_Real_IA" => $rawAiResponse
        ]);
        exit();
    }
}