<?php
declare(strict_types=1);
/**
 * This file is part of the AI Pic Repository Page Component plugin for ILIAS, which allows
 * users of your platform to add an image component to their pages, generated by an external AI model.
 * This plugin is created and maintained by SURLABS.
 *
 * The AI Pic Repository Page Component plugin for ILIAS is open-source and licensed under GPL-3.0.
 * For license details, visit https://www.gnu.org/licenses/gpl-3.0.en.html.
 *
 * To report bugs or participate in discussions, visit the Mantis system and filter by
 * the category "AI Pic" at https://mantis.ilias.de.
 *
 * More information and source code are available at:
 * https://github.com/surlabs/AIPicForILIAS
 *
 * If you need support, please contact the maintainer of this software at:
 * info@surlabs.com
 *
 */

use ILIAS\ResourceStorage\Flavour\Definition\PagesToExtract;
use ILIAS\ResourceStorage\Identification\ResourceIdentification;
use ILIAS\UI\Renderer;
use ILIAS\UI\Component\Input\Container\Form\Standard;
use platform\AIPicConfig;

/**
 * Class ilAIPicPluginGUI
 * @authors Sergio Santiago, Abraham Morales <info@surlabs.com>
 * @ilCtrl_isCalledBy ilAIPicPluginGUI: ilRepositoryGUI, ilAdministrationGUI, ilObjPluginDispatchGUI, ilAIPicEditorGUI, ilPCPluggedGUI
 * @ilCtrl_Calls      ilAIPicPluginGUI: ilPermissionGUI, ilInfoScreenGUI, ilObjectCopyGUI, ilCommonActionDispatcherGUI, ilExportGUI, ilAIPicEditorGUI, ilObjRootFolderGUI
 */

class ilAIPicPluginGUI extends ilPageComponentPluginGUI
{
    public const LP_SESSION_ID = 'xaip_lp_session_state';
    private Renderer $renderer;
    private ilCtrlInterface $ctrl;
    private ilGlobalTemplateInterface $tpl;
    private UploadServiceAIPicGUI $uploader;
    private ilAIPicEditorGUI $editorGUI;
    protected static int $id_counter = 0;

    public function __construct()
    {
        parent::__construct();

        global $DIC;
        $this->uploader = new UploadServiceAIPicGUI();
        $this->renderer = $DIC->ui()->renderer();
        $this->ctrl = $DIC->ctrl();
        $this->tpl = $DIC->ui()->mainTemplate();
    }

    /**
     * @throws ilCtrlException
     */
    public function executeCommand(): void
    {
        global $ilCtrl;
        $next_class = $ilCtrl->getNextClass();

        switch($next_class)
        {
            default:
                // perform valid commands
                $cmd = $ilCtrl->getCmd();
                if (in_array($cmd, array("create", "save", "edit", "edit2", "update", "cancel", "sendPrompt", "insert", "saveImage", "update")))
                {
                    $this->$cmd();
                }
                break;
        }
    }

    /**
     * @throws Exception
     */
    private function generateImageCreator(): AIPicRequestInterface {
        $config = new AIPicConfig();
        $config->loadFromDB();
        $AIPicProvider = AIPicRequestImpl::from($config);

        return $AIPicProvider;
    }

    /**
     * @throws ilCtrlException
     * @throws Exception
     */
    public function insert(): void
    {
        global $DIC, $ilCtrl;

        $this->editorGUI = new ilAIPicEditorGUI($this->plugin, $this->generateImageCreator());
        $form = $this->editorGUI->getPromptForm();
        $request = $DIC->http()->request();
        $query = $DIC->http()->wrapper()->query();
        $refinery = $DIC->refinery();
        $action = $query->retrieve("cmd", $refinery->to()->string());
        $actionDesired = $query->has("methodDesired") ? $query->retrieve("methodDesired", $refinery->to()->string()) : null;

        $ilCtrl->setParameterByClass('ilAIPicPluginGUI', 'methodDesired', 'sendPrompt');

        if ($request->getMethod() == "POST" && $action != "post" && $actionDesired == "saveImage") {
            $form = $form->withRequest($request);

            if ($form->getError() !== null) {
                $this->renderEditorWithForm($form);
                return;
            }

            $result = $form->getData();

            if (isset($result) && count($result) > 0 && !empty($result[0]['file'])) {
                $result[0]['imageId'] = $result[0]['file'][0];
                $result[0]["legacyFileName"] = $this->uploader->getInfoResult($result[0]["file"][0])->getName();
                $result[0]["fileName"] = $result[0]["file"][0];
                unset($result[0]['file']);

                try {
                    $savedSuccess = $this->createElement($result[0]);
                    if ($savedSuccess) {
                        $this->returnToParent();
                        return;
                    } else {
                        $DIC->ui()->mainTemplate()->setOnScreenMessage('failure', "Error: ILIAS rechazó la actualización de la página.", true);
                    }
                } catch (Throwable $e) {
                    // EL CHIVATO DEFINITIVO: Ahora nos dirá el archivo y la línea exacta
                    $errorMsg = "Error en " . basename($e->getFile()) . " (Línea " . $e->getLine() . "): " . $e->getMessage();
                    $DIC->ui()->mainTemplate()->setOnScreenMessage('failure', $errorMsg, true);
                }

                $this->renderEditorWithForm($form);
                return;
            } else {
                $DIC->ui()->mainTemplate()->setOnScreenMessage('failure', "Falta la imagen.", true);
                $this->renderEditorWithForm($form);
                return;
            }
        } else {
            $this->renderEditorWithForm($form);
        }
    }

    /**
     * @throws ilCtrlException
     * @throws Exception
     */
    public function edit(): void
    {
        $this->editorGUI = new ilAIPicEditorGUI($this->plugin, $this->generateImageCreator());
        $form = $this->editorGUI->getPromptFormWithProperties($this->getProperties());

        $file_name = null;
        if (!empty($this->getProperties()["imageId"])) {
            $file_name = $this->resolveImageSrc($this->getProperties()["imageId"]);
        }

        $this->renderEditorWithForm($form, $file_name);
    }

    /**
     * @throws ilCtrlException
     */
    public function update(): void
    {
        global $DIC;

        $this->editorGUI = new ilAIPicEditorGUI($this->plugin, $this->generateImageCreator());
        $form = $this->editorGUI->getPromptFormWithProperties($this->getProperties());
        $form = $form->withRequest($DIC->http()->request());

        if ($form->getError() !== null) {
            $this->renderEditorWithForm($form);
            return;
        }

        $result = $form->getData();

        if (isset($result) && count($result) > 0) {
            if (!empty($result[0]['file'])) {
                if (array_key_exists("imageId", $this->getProperties())) {
                    $this->removeImageById($this->getProperties()["imageId"]);
                }
                $result[0]['imageId'] = $result[0]['file'][0];
                $result[0]["legacyFileName"] = $this->uploader->getInfoResult($result[0]["file"][0])->getName();
                $result[0]["fileName"] = $result[0]["file"][0];
                unset($result[0]['file']);
            } else {
                $result[0]['imageId'] = $this->getProperties()["imageId"];
                unset($result[0]['file']);
            }

            $this->updateElement($result[0]);

            try {
                $this->updateMediaObjectProperties($result[0]);
                $this->returnToParent();
                return;
            } catch (Throwable $e) {
                $errorMsg = "Error en updateMediaObject (Línea " . $e->getLine() . "): " . $e->getMessage();
                $DIC->ui()->mainTemplate()->setOnScreenMessage('failure', $errorMsg, true);
            }
        }

        $this->renderEditorWithForm($form);
    }

    /**
     * @throws ilCtrlException
     */
    public function create(): void
    {
        $this->ctrl->redirect($this, 'insert');
    }

    /**
     * Override createElement to create MediaObject instead of plugin object
     * @throws Exception|Throwable
     */
    public function createElement(array $a_properties): bool
    {
        global $DIC;

        $imageId = $a_properties["imageId"] ?? '';
        if (empty($imageId)) {
            throw new Exception("Image ID is empty. Please generate an image before submitting.");
        }

        // 1. Create a new native Media Object
        $mob = new ilObjMediaObject();
        $title = "AIPic_Image";
        if (!empty($a_properties["title"]) && trim($a_properties["title"]) !== "") {
            $title = trim($a_properties["title"]);
        }
        $mob->setTitle($title);
        if (!empty($a_properties["prompt"])) {
            $mob->setDescription(trim($a_properties["prompt"]));
        }
        $mob->create();
        $mob->createDirectory(); // Create physical directory

        // 2. Locate the physical source file
        $src_file = null;
        try {
            // Try native IRSS first
            $irss = $DIC->resourceStorage();
            $rid = new \ILIAS\ResourceStorage\Identification\ResourceIdentification($imageId);
            $src_file = $irss->consume()->src($rid)->getSrc();
        } catch (Throwable $e) {
            // Fallback: Check if the ID belongs to another Media Object
            if (ilObject::_lookupType((int)$imageId) === 'mob') {
                $tempMob = new ilObjMediaObject((int)$imageId);
                $mediaItems = $tempMob->getMediaItems();
                if (!empty($mediaItems)) {
                    $src_file = ilObjMediaObject::_getDirectory($tempMob->getId()) . "/" . $mediaItems[0]->getLocation();
                }
            }
            // Fallback: Check if the ID belongs to a classic ilObjFile
            elseif (ilObject::_lookupType((int)$imageId) === 'file') {
                $tempFile = new ilObjFile((int)$imageId, false);
                $src_file = $tempFile->getFile();
            }

            if (!$src_file || !file_exists($src_file)) {
                $mob->delete();
                throw new Exception("File for ID [$imageId] was not found on disk. Please regenerate the image.");
            }
        }

        // 3. Copy file to the new Media Object directory
        $rawFilename = $a_properties["legacyFileName"] ?? ("aipic_" . time() . ".png");
        $filename = basename($rawFilename);
        $dest_file = ilObjMediaObject::_getDirectory($mob->getId()) . "/" . $filename;

        if ($src_file && filter_var($src_file, FILTER_VALIDATE_URL)) {
            try {
                $irss = $DIC->resourceStorage();
                $rid = new \ILIAS\ResourceStorage\Identification\ResourceIdentification($imageId);
                $stream = $irss->consume()->stream($rid)->getStream();
                file_put_contents($dest_file, $stream->getContents());
            } catch (Throwable $e) {
                // Silent fallback
            }
        } elseif ($src_file && file_exists($src_file)) {
            copy($src_file, $dest_file);
        }

        // Register and copy the file into the IRSS container natively
        $mediaItem = $mob->addMediaItemFromLocalFile("Standard", $dest_file, $filename);
        $mediaItem->setNr(1);

        $this->applyLayoutProperties($mediaItem, $a_properties);
        $mob->update();

        // 4. Create alias and insert it into the page DOM
        $pc_media = new ilPCMediaObject($this->getPCGUI()->getPage());
        $pc_media->setMediaObject($mob);

        // Detect insertion position
        $position = method_exists($this->getPCGUI(), 'getPosition') ? $this->getPCGUI()->getPosition() : "after";

        $pc_media->createAlias($this->getPCGUI()->getPage(), $this->getPCGUI()->getHierId(), $position);

        // Apply CSS styles, alignment and alternate text
        $this->applyAliasProperties($pc_media, $a_properties);

        // Save changes to the page
        $is_updated = $this->getPCGUI()->getPage()->update();

        return $is_updated === true;
    }

    /**
     * Update MediaObject and its page alias properties
     */
    private function updateMediaObjectProperties(array $a_properties): void
    {
        // Legacy UUID imageIds cannot be updated via ilObjMediaObject — skip gracefully
        if ($this->isLegacyImageId($a_properties["imageId"] ?? '')) {
            return;
        }

        try {
            $mob = new ilObjMediaObject((int)$a_properties["imageId"]);
            if ($mob->getId()) {
                $title = "AIPic_" . $mob->getId();
                if (!empty($a_properties["title"]) && trim($a_properties["title"]) !== "") {
                    $title = trim($a_properties["title"]);
                }
                $mob->setTitle($title);

                if (!empty($a_properties["prompt"])) {
                    $mob->setDescription(trim($a_properties["prompt"]));
                }

                // Save standard changes
                $mob->update();

                // Load XML element from the page DOM to update layout and CSS
                $page = $this->getPCGUI()->getPage();
                $hier_id = $this->getPCGUI()->getHierId();

                $pc_media = new ilPCMediaObject($page);
                $pc_media->readMediaObjectNode($page, $hier_id);

                $this->applyAliasProperties($pc_media, $a_properties);
                $page->update();
            }
        } catch (Throwable $e) {
            global $DIC;
            $errorMsg = "Error in updateMediaObject (Line " . $e->getLine() . "): " . $e->getMessage();
            $DIC->ui()->mainTemplate()->setOnScreenMessage('failure', $errorMsg, true);
            $DIC->logger()->root()->error($errorMsg);
        }
    }

    /**
     * Apply layout properties to MediaItem
     */
    private function applyLayoutProperties(ilMediaItem $mediaItem, array $properties): void
    {
        if (isset($properties["widthInput"]) && $properties["widthInput"] > 0) {
            // With no multiplier, image is too small
            $withMultiplier = $properties["widthInput"] * 12;
            $mediaItem->setWidth((string)$withMultiplier);
        }
    }

    /**
     * Apply native layout properties to the DOM node
     */
    private function applyAliasProperties(ilPCMediaObject $pc_media, array $properties): void
    {
        // Style class
        if (!empty($properties["styleClass"])) {
            $pc_media->setClass($properties["styleClass"]);
        }

        $dom_node = $pc_media->getDomNode();
        $dom_doc = $pc_media->getDomDoc();

        if (!$dom_node || !$dom_doc) {
            return;
        }

        $xpath = new DOMXPath($dom_doc);

        // Alignment
        $alignment = $properties["aligments"] ?? "Center";
        $horizontal_align = match ($alignment) {
            "Center" => "Center",
            "Left" => "Left",
            "Right" => "Right",
            "LeftFloat" => "Left, Floating",
            "RightFloat" => "Right, Floating",
            default => "Center",
        };

        $layout_nodes = $xpath->query(".//Layout", $dom_node);
        if ($layout_nodes->length > 0) {
            $layout_nodes->item(0)->setAttribute("HorizontalAlign", $horizontal_align);
        }

        // Set standard caption from prompt
        if (!empty($properties["prompt"]) && method_exists($pc_media, 'setStandardCaption')) {
            $pc_media->setStandardCaption($properties["prompt"]);
        }

        // Alt text representation
        if (!empty($properties["textRepresentation"]) && method_exists($pc_media, 'setStandardTextRepresentation')) {
            $pc_media->setStandardTextRepresentation($properties["textRepresentation"]);
        }
    }

    // -------------------------------------------------------------------------
    // Helpers: legacy vs. new imageId format
    // -------------------------------------------------------------------------

    /**
     * Returns true if the given imageId is a legacy IRSS UUID (non-numeric).
     * New-format imageIds are the integer ID of an ilObjMediaObject.
     */
    private function isLegacyImageId(string $imageId): bool
    {
        return !ctype_digit(trim($imageId));
    }

    /**
     * Resolve the web-accessible image URL for both legacy (IRSS UUID) and
     * new (ilObjMediaObject integer ID) imageId formats.
     *
     * Returns null if the image resource cannot be found.
     */
    private function resolveImageSrc(string $imageId): ?string
    {
        if ($imageId === '') {
            return null;
        }

        if ($this->isLegacyImageId($imageId)) {
            // Legacy format: IRSS UUID — resolve via ResourceStorage
            try {
                global $DIC;
                $irss = $DIC->resourceStorage();
                $rid  = new \ILIAS\ResourceStorage\Identification\ResourceIdentification($imageId);
                return $irss->consume()->src($rid)->getSrc();
            } catch (Throwable $e) {
                return null;
            }
        }

        // New format: integer mob ID — resolve via ilObjMediaObject
        try {
            $mob = new ilObjMediaObject((int)$imageId);
            if (!$mob->getId()) {
                return null;
            }
            $mediaItems = $mob->getMediaItems();
            if (empty($mediaItems)) {
                return null;
            }
            $mediaItem = $mediaItems[0];
            return ilObjMediaObject::_getURL($mob->getId()) . '/' . $mediaItem->getLocation();
        } catch (Throwable $e) {
            return null;
        }
    }

    /**
     * Delete a stored image by its imageId, handling both legacy (IRSS UUID)
     * and new (ilObjMediaObject integer ID) formats.
     */
    private function removeImageById(string $imageId): void
    {
        if ($imageId === '') {
            return;
        }

        if ($this->isLegacyImageId($imageId)) {
            // Legacy: remove from IRSS
            $this->uploader->removeFromOutside($imageId);
        } else {
            // New: delete the ilObjMediaObject
            try {
                $mob = new ilObjMediaObject((int)$imageId);
                if ($mob->getId()) {
                    $mob->delete();
                }
            } catch (Throwable $e) {
                // Silent: mob may already be gone
            }
        }
    }

    /**
     * Render the editor form and load assets
     */
    private function renderEditorWithForm(Standard $form, ?string $file_name = null): void
    {
        global $tpl;

        $this->editorGUI->manageDownloadImage();
        $image = $this->editorGUI->generateImage($file_name);
        $res = $this->editorGUI->renderForm($form) . $image;

        $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/downloadImage.js");
        $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/callSaveEndpoint.js");
        $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/widthInput.js");
        $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/alignButtons.js");
        $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/resendForm.js");
        $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/adjustImage.js");
        $tpl->addCss("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/css/aIPic_sheet.css");

        $this->tpl->setContent($res);
    }

    /**
     * @throws ilTemplateException
     * @throws Exception
     */
    public function getElementHTML(string $a_mode, array $a_properties, string $plugin_version): string
    {
        if (empty($a_properties["imageId"])) {
            return "";
        }

        $this->editorGUI = new ilAIPicEditorGUI($this->plugin, $this->generateImageCreator());

        $file_name = $this->resolveImageSrc($a_properties["imageId"]);
        if ($file_name === null) {
            // Image resource not found (legacy element whose IRSS resource no longer exists)
            return "";
        }
        $a_properties["fileName"] = $file_name;

        $tpl = new ilTemplate("aIPic_element.html", true, true, "Customizing/global/plugins/Services/COPage/PageComponent/AIPic");
        $this->tpl->addCss("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/css/aIPic_sheet.css");

        $tpl->setVariable("ID", date_create()->format('Y-m-d_H-i-s'));
        $tpl->setVariable("SCALE_WRAPPER_WIDTH", $a_properties["widthInput"]);

        $raw_alignment = $a_properties["aligments"] ?? "center";
        $alignment = empty($raw_alignment) ? "left" : $raw_alignment;
        $tpl->setVariable("ALIGNMENT", $alignment);

        $tpl->setVariable("TEMPLATES_DIR", "Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates");
        $tpl->setVariable("PLUGIN_DIR", "Customizing/global/plugins/Services/COPage/PageComponent/AIPic");
        $tpl->setVariable("IMAGE_URL", $a_properties["fileName"]);
        $tpl->setVariable("PROPERTIES", json_encode($a_properties));

        return $tpl->get();
    }
}