<?php
declare(strict_types=1);
/**
 * This file is part of the AI Pic Repository Page Component plugin for ILIAS, which allows
 * users of your platform to add an image component to their pages, generated by an external AI model.
 * This plugin is created and maintained by SURLABS.
 *
 * The AI Pic Repository Page Component plugin for ILIAS is open-source and licensed under GPL-3.0.
 * For license details, visit https://www.gnu.org/licenses/gpl-3.0.en.html.
 *
 * To report bugs or participate in discussions, visit the Mantis system and filter by
 * the category "AI Pic" at https://mantis.ilias.de.
 *
 * More information and source code are available at:
 * https://github.com/surlabs/AIPicForILIAS
 *
 * If you need support, please contact the maintainer of this software at:
 * info@surlabs.com
 *
 */

/**
 * Class AIPicRequestAbstract
 * @authors Sergio Santiago, Abraham Morales <info@surlabs.com>
 */

abstract class AIPicRequestAbstract implements AIPicRequestInterface
{
    private CurlHandle $ch;
    protected array $header = [];
    protected array $body = [];
    protected string $promptContext = "";
    protected string $url;
    protected string|bool|null $response;
    protected string $requestPromptKey = "prompt";
    protected string $responseKey;
    protected ?string $responseSubkey = null;

    public function __construct() {
        $this->ch = curl_init();
    }

    public function withHeader(array $header): AIPicRequestAbstract {
        $this->header = $header;
        return $this;
    }

    public function withBody(array $body): AIPicRequestAbstract {
        $this->body = $body;
        return $this;
    }

    public function withPromptContext(string $promptContext): AIPicRequestAbstract {
        $this->promptContext = $promptContext;
        return $this;
    }

    public function withUrl(string $url): AIPicRequestAbstract {
        $this->url = $url;
        return $this;
    }

    public function withRequestPromptKey(string $requestPromptKey): AIPicRequestAbstract {
        $this->requestPromptKey = $requestPromptKey;
        return $this;
    }

    public function withResponseKey(string $responseKey): AIPicRequestAbstract {
        $this->responseKey = $responseKey;
        return $this;
    }

    public function withResponseSubkey(string $responseSubkey): AIPicRequestAbstract {
        $this->responseSubkey = $responseSubkey;
        return $this;
    }

    public function getDataArray(): array {
        $res = [];
        if(isset($this->response)) {
            $responseDecoded = $this->response ? json_decode($this->response, true): [];

            if (!is_array($responseDecoded)) {
                return $res;
            }

            if ($this->responseKey !== '' && array_key_exists($this->responseKey, $responseDecoded)) {
                $res = $responseDecoded[$this->responseKey];
            } elseif ($this->responseSubkey !== null && array_key_exists($this->responseSubkey, $responseDecoded)) {
                $res = [[
                    $this->responseSubkey => $responseDecoded[$this->responseSubkey]
                ]];
            }
        }
        return $res;
    }

    public function getImagesUrlsArray(): array {
        $data = $this->getDataArray();
        $imagesUrls = [];
        if(isset($this->responseSubkey)) {
            if (!is_array($data)) {
                return $imagesUrls;
            }

            foreach($data as $image) {
                if (is_array($image) && array_key_exists($this->responseSubkey, $image)) {
                    $imagesUrls[] = $image[$this->responseSubkey];
                }
            }
        } elseif (!is_array($data) || array_is_list($data)) {
            $imagesUrls[] = $data;
        } else {
            $imagesUrls[] = json_encode($data);
        }

        return $imagesUrls;
    }

    public function getImagesPayloadArray(): array
    {
        $images = [];

        foreach ($this->getImagesUrlsArray() as $value) {
            if (!is_string($value) || trim($value) === '') {
                continue;
            }

            $mode = filter_var($value, FILTER_VALIDATE_URL) ? 'url' : 'base64';
            $images[] = [
                'mode' => $mode,
                'value' => $value,
                'mime' => $mode === 'base64' ? 'image/png' : null,
            ];
        }

        return $images;
    }

    public function sendPrompt(string $prompt): bool|string {
        if(strlen($prompt) > 0) {
            $this->body[$this->requestPromptKey] = $this->promptContext. " " . $prompt;
            $bodyRequest = json_encode($this->getBody());
            $fullPrompt = $this->promptContext . " " . $prompt;

            if (str_contains($this->url, 'googleapis.com')) {
                $bodyRequest = json_encode([
                    "contents" => [
                        [
                            "parts" => [
                                ["text" => $fullPrompt]
                            ]
                        ]
                    ]
                ]);
            } else {
                $this->body[$this->requestPromptKey] = $fullPrompt;
                $bodyRequest = json_encode($this->getBody());
            }

            curl_setopt($this->ch, CURLOPT_URL, $this->url);
            curl_setopt($this->ch, CURLOPT_POST, true);
            curl_setopt($this->ch, CURLOPT_POSTFIELDS, $bodyRequest);
            curl_setopt($this->ch, CURLOPT_HTTPHEADER, $this->header);
            curl_setopt($this->ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($this->ch, CURLOPT_TIMEOUT, 120);

            $rawResponse = curl_exec($this->ch);
            $httpCode = curl_getinfo($this->ch, CURLINFO_HTTP_CODE);
            $curlError = curl_error($this->ch);

            // Handle network or API errors silently
            if ($rawResponse === false || $httpCode >= 400) {
                $realError = $rawResponse !== false ? $rawResponse : $curlError;
                error_log("AIPic Plugin Error (HTTP $httpCode) - Real IA Reason: " . $realError);

                // Return i18n key for UI
                $genericError = [
                    "error" => true,
                    "error_key" => "err_api_connection"
                ];

                $this->response = json_encode($genericError);
                return $this->response;
            }

            if (str_contains($this->url, 'googleapis.com') && is_string($rawResponse)) {
                $decoded = json_decode($rawResponse, true);
                $parts = $decoded['candidates'][0]['content']['parts'] ?? [];
                $b64 = null;

                foreach($parts as $part) {
                    if (isset($part['inlineData']['data'])) {
                        $b64 = $part['inlineData']['data'];
                        break;
                    } elseif (isset($part['inline_data']['data'])) {
                        $b64 = $part['inline_data']['data'];
                        break;
                    }
                }

                if ($b64) {
                    // Repackage to match DALL-E format
                    $rawResponse = json_encode([
                        "data" => [
                            ["b64_json" => $b64]
                        ]
                    ]);
                } else {
                    // Handle Gemini safety blocks (HTTP 200 without image data)
                    error_log("AIPic Plugin Error - Gemini blocked the content or did not return an image: " . $rawResponse);
                    $genericError = [
                        "error" => true,
                        "error_key" => "err_api_safety"
                    ];
                    $rawResponse = json_encode($genericError);
                }
            }

            $this->response = $rawResponse;
            return $this->response;
        }
        return false;
    }

    public function getHeader(): array {
        return $this->header;
    }

    public function getBody(): array {
        return $this->body;
    }

    public function getResponse(): string|bool|null {
        return $this->response;
    }

    public function getPromptContext(): string
    {
        return $this->promptContext;
    }

    public function getUrl(): string
    {
        return $this->url;
    }

    public function getRequestPromptKey(): string
    {
        return $this->requestPromptKey;
    }

    public function getResponseKey(): string
    {
        return $this->responseKey;
    }

    public function getResponseSubkey(): ?string
    {
        return $this->responseSubkey;
    }

    public static function getArrayFromString(string $txt): array {
        $dataLst = explode(",", $txt);
        $data = [];
        foreach($dataLst as $d) {
            if(str_contains($d, ":")) {
                $entries = explode(":", $d);
                $data[] = $entries[0] . ": " . $entries[1];
            }
        }
        return $data;
    }
}