<?php
declare(strict_types=1);
/**
 *  This file is part of the AI Pic Repository Page Component plugin for ILIAS, which allows
 *  users of your platform to add an image component to their pages, generated by an external AI model.
 *  This plugin is created and maintained by SURLABS.
 *
 *  The AI Pic Repository Page Component plugin for ILIAS is open-source and licensed under GPL-3.0.
 *  For license details, visit https://www.gnu.org/licenses/gpl-3.0.en.html.
 *
 *  To report bugs or participate in discussions, visit the Mantis system and filter by
 *  the category "AI Pic" at https://mantis.ilias.de.
 *
 *  More information and source code are available at:
 *  https://github.com/surlabs/AIPicForILIAS
 *
 *  If you need support, please contact the maintainer of this software at:
 *  info@surlabs.com
 *
 */

use ILIAS\ResourceStorage\Flavour\Definition\PagesToExtract;
use ILIAS\ResourceStorage\Identification\ResourceIdentification;
use ILIAS\UI\Renderer;
use ILIAS\UI\Component\Input\Container\Form\Standard;
use platform\AIPicConfig;

/**
 * Class ilAIPicPluginGUI
 * @authors Sergio Santiago, Abraham Morales <info@surlabs.com>
 * @ilCtrl_isCalledBy ilAIPicPluginGUI: ilRepositoryGUI, ilAdministrationGUI, ilObjPluginDispatchGUI, ilAIPicEditorGUI, ilPCPluggedGUI
 * @ilCtrl_Calls      ilAIPicPluginGUI: ilPermissionGUI, ilInfoScreenGUI, ilObjectCopyGUI, ilCommonActionDispatcherGUI, ilExportGUI, ilAIPicEditorGUI, ilObjRootFolderGUI
 */

class  ilAIPicPluginGUI extends ilPageComponentPluginGUI
{
    public const LP_SESSION_ID = 'xaip_lp_session_state';
    private Renderer $renderer;
    private ilCtrlInterface $ctrl;
    private ilGlobalTemplateInterface $tpl;
    private UploadServiceAIPicGUI $uploader;
    private ilAIPicEditorGUI $editorGUI;
    protected static int $id_counter = 0;

    public function __construct()
    {
        parent::__construct();

        global $DIC;
        $this->uploader = new UploadServiceAIPicGUI();
        $this->renderer = $DIC->ui()->renderer();
        $this->ctrl = $DIC->ctrl();
        $this->tpl = $DIC->ui()->mainTemplate();
    }

    /**
     * @throws ilCtrlException
     */
    public function update(): void
    {
        global $tpl, $DIC, $ilCtrl;

        $this->editorGUI = new ilAIPicEditorGUI($this->plugin, $this->generateImageCreator());
        $form = $this->editorGUI->getPromptForm();
        $form = $form->withRequest($DIC->http()->request());
        $result = $form->getData();

        if($form->getError() === null) {
            if(isset(end($result)['file']) && count($result) > 0 && count($result[0]['file']) > 0) {
                if(array_key_exists("imageId", $this->getProperties())) {
                    $this->uploader->removeFromOutside($this->getProperties()["imageId"]);
                }
                $result[0]['imageId'] = $result[0]['file'][0];
                $result[0]["legacyFileName"] = $this->uploader->getInfoResult($result[0]["file"][0])->getName();
                $result[0]["fileName"] = $result[0]["file"][0];
                unset($result[0]['file']);
            } else {

                $result[0]['imageId'] = $this->getProperties()["imageId"];
                unset($result[0]['file']);
            }

            $this->updateElement($result[0]);
            $this->returnToParent();
        } else {
            $ilCtrl->setParameterByClass('ilAIPicPluginGUI', 'methodDesired', 'sendPrompt');
            $this->editorGUI->manageDownloadImage();
            $image = $this->editorGUI->generateImage();
            $res = $this->editorGUI->renderForm($form) . $image;

            $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/downloadImage.js");
            $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/callSaveEndpoint.js");
            $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/widthInput.js");
            $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/alignButtons.js");
            $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/resendForm.js");
            $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/adjustImage.js");
            $tpl->addCss("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/css/aIPic_sheet.css");
            $this->tpl->setContent($res);
        }
    }

    // PageComponent methods

    /**
     * @throws ilCtrlException
     */
    public function executeCommand(): void
    {
        global $ilCtrl;
        $next_class = $ilCtrl->getNextClass();

        switch($next_class)
        {
            default:
                // perform valid commands
                $cmd = $ilCtrl->getCmd();
                if (in_array($cmd, array("create", "save", "edit", "edit2", "update", "cancel", "sendPrompt", "insert", "saveImage", "update")))
                {
                    $this->$cmd();
                }
                break;
        }
    }

    /**
     * @throws Exception
     */
    private function generateImageCreator(): AIPicRequestInterface {
        $config = new AIPicConfig();
        $config->loadFromDB();
        $AIPicProvider = AIPicRequestImpl::from($config);

        return $AIPicProvider;
    }

    /**
     * @throws ilCtrlException
     * @throws Exception
     */
    public function insert(): void
    {
        global $tpl, $DIC, $ilCtrl;

        $DIC->logger()->root()->info("FORM LOADED");
        $this->editorGUI = new ilAIPicEditorGUI($this->plugin, $this->generateImageCreator());
        $form = $this->editorGUI->getPromptForm();
        $request = $DIC->http()->request();
        $query = $DIC->http()->wrapper()->query();
        $refinery = $DIC->refinery();
        $action = $query->retrieve("cmd", $refinery->to()->string());
        $actionDesired = $query->has("methodDesired") ? $query->retrieve("methodDesired", $refinery->to()->string()) : null;

        $ilCtrl->setParameterByClass('ilAIPicPluginGUI', 'methodDesired', 'sendPrompt');

        if ($request->getMethod() == "POST" && $action != "post" && $actionDesired == "saveImage") {
            $request = $DIC->http()->request();
            $form = $this->editorGUI->getPromptForm();
            $form = $form->withRequest($request);
            $result = $form->getData();

            if(isset($result) && count($result) > 0 && count($result[0]['file']) > 0) {
                $result[0]['imageId'] = $result[0]['file'][0];

                $result["legacyFileName"] = $this->uploader->getInfoResult($result[0]["file"][0])->getName();
                $result["fileName"] = $result[0]["file"][0];
                unset($result[0]['file']);
                $this->createElement($result[0]);
            }

            $this->returnToParent();

        } else {
            // Check if we can download the image
            $this->editorGUI->manageDownloadImage();

            // Generate the image div
            $image = $this->editorGUI->generateImage();

            $res = $this->editorGUI->renderForm($form) .
                $image;

            $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/downloadImage.js");
            $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/callSaveEndpoint.js");
            $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/widthInput.js");
            $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/alignButtons.js");
            $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/resendForm.js");
            $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/adjustImage.js");

            $tpl->addCss("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/css/aIPic_sheet.css");

            $this->tpl->setContent($res);
        }
    }

    /**
     * @throws ilCtrlException
     * @throws Exception
     */
    public function edit(): void
    {
        global $tpl, $DIC, $ilCtrl;

        $this->editorGUI = new ilAIPicEditorGUI($this->plugin, $this->generateImageCreator());
        $form = $this->editorGUI->getPromptFormWithProperties($this->getProperties());
        $irss = $DIC->resourceStorage();
        $file_name = $irss->consume()->src(new ResourceIdentification($this->getProperties()["imageId"]))->getSrc();
        $image = $this->editorGUI->generateImage($file_name ?? null);

        $res = $this->renderer->render($form) . $image;

        $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/downloadImage.js");
        $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/callSaveEndpoint.js");
        $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/widthInput.js");
        $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/alignButtons.js");
        $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/resendForm.js");
        $tpl->addJavaScript("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/js/adjustImage.js");

        $tpl->addCss("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/css/aIPic_sheet.css");

        $this->tpl->setContent($res);
    }

    /**
     * @throws ilCtrlException
     */
    public function create(): void
    {
        $this->ctrl->redirect($this, 'insert');
    }

    /**
     * Override createElement to create MediaObject instead of plugin object
     * This ensures images persist even if plugin is uninstalled
     */
    public function createElement(array $a_properties): bool
    {
        global $DIC;

        try {
            $mob = new ilObjMediaObject((int)$a_properties["imageId"]);

            if (!$mob->getId()) {
                throw new Exception("MediaObject not found with ID: " . $a_properties["imageId"]);
            }

            $mediaItems = $mob->getMediaItems();
            if (empty($mediaItems)) {
                throw new Exception("No MediaItems found for MediaObject ID: " . $a_properties["imageId"]);
            }

            $mediaItem = $mediaItems[0];

            $this->applyLayoutProperties($mediaItem, $a_properties);
            $mediaItem->update();

            $pc_media = new ilPCMediaObject($this->getPCGUI()->getPage());
            $pc_media->setMediaObject($mob);
            $pc_media->createAlias(
                $this->getPCGUI()->getPage(),
                $this->getPCGUI()->getHierId(),
                ""
            );

            $this->applyAlignment($pc_media, $a_properties);

            $this->updated = $this->getPCGUI()->getPage()->update();

            return $this->updated === true;

        } catch (Exception $e) {
            // Log error
            $DIC->logger()->root()->error("Failed to create MediaObject: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Apply layout properties to MediaItem
     */
    private function applyLayoutProperties(ilMediaItem $mediaItem, array $properties): void
    {
        if (isset($properties["widthInput"]) && $properties["widthInput"] > 0) {
            // With no multiplier, image is too small
            $withMultiplier = $properties["widthInput"] * 12;
            $mediaItem->setWidth((string)$withMultiplier);
        }
    }

    /**
     * Apply alignment to MediaObject layout
     */
    private function applyAlignment(ilPCMediaObject $pc_media, array $properties): void
    {
        if (!isset($properties["aligments"])) {
            return;
        }

        $alignment = $properties["aligments"];
        $horizontal_align = match ($alignment) {
            "center" => "Center",
            "right" => "Right",
            default => "Left",
        };

        // Get the MediaAlias node and update layout
        $dom_node = $pc_media->getDomNode();
        if ($dom_node) {
            $xpath = new DOMXPath($pc_media->getDomDoc());
            $layout_nodes = $xpath->query(".//Layout", $dom_node);
            if ($layout_nodes->length > 0) {
                $layout_nodes->item(0)->setAttribute("HorizontalAlign", $horizontal_align);
            }
        }
    }

    /**
     * @throws ilTemplateException
     * @throws Exception
     */
    public function getElementHTML(string $a_mode, array $a_properties, string $plugin_version): string
    {
        global $DIC;

        if (empty($a_properties["imageId"])) {
            return "";
        }

        $this->editorGUI = new ilAIPicEditorGUI($this->plugin, $this->generateImageCreator());

        $irss = $DIC->resourceStorage();
        $file_name = $irss->consume()->src(new ResourceIdentification($a_properties["imageId"]))->getSrc();
        $a_properties["fileName"] = $file_name;

        $tpl = new ilTemplate("aIPic_element.html", true, true, "Customizing/global/plugins/Services/COPage/PageComponent/AIPic");
        $this->tpl->addCss("./Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates/css/aIPic_sheet.css");

        $tpl->setVariable("ID", date_create()->format('Y-m-d_H-i-s'));
        $tpl->setVariable("SCALE_WRAPPER_WIDTH", $a_properties["widthInput"]);

        $raw_alignment = $a_properties["aligments"] ?? "center";
        $alignment = empty($raw_alignment) ? "left" : $raw_alignment;
        $tpl->setVariable("ALIGNMENT", $alignment);

        $tpl->setVariable("TEMPLATES_DIR", "Customizing/global/plugins/Services/COPage/PageComponent/AIPic/templates");
        $tpl->setVariable("PLUGIN_DIR", "Customizing/global/plugins/Services/COPage/PageComponent/AIPic");
        $tpl->setVariable("IMAGE_URL", $a_properties["fileName"]);
        $tpl->setVariable("PROPERTIES", json_encode($a_properties));

        return $tpl->get();

    }
}