<?php
declare(strict_types=1);
/**
 *  This file is part of the AI Pic Repository Page Component plugin for ILIAS, which allows
 *  users of your platform to add an image component to their pages, generated by an external AI model.
 *  This plugin is created and maintained by SURLABS.
 *
 *  The AI Pic Repository Page Component plugin for ILIAS is open-source and licensed under GPL-3.0.
 *  For license details, visit https://www.gnu.org/licenses/gpl-3.0.en.html.
 *
 *  To report bugs or participate in discussions, visit the Mantis system and filter by
 *  the category "AI Pic" at https://mantis.ilias.de.
 *
 *  More information and source code are available at:
 *  https://github.com/surlabs/AIPicForILIAS
 *
 *  If you need support, please contact the maintainer of this software at:
 *  info@surlabs.com
 *
 */

 /**
 * Class AIPicRequestAbstract
 * @authors Sergio Santiago, Abraham Morales <info@surlabs.com>
 */

abstract class AIPicRequestAbstract implements AIPicRequestInterface
{
    private CurlHandle $ch;
    protected array $header = [];
    protected array $body = [];
    protected string $promptContext = "";
    protected string $url;
    protected string|bool|null $response;
    protected string $requestPromptKey = "prompt";
    protected string $responseKey;
    protected ?string $responseSubkey = null;

    public function __construct() {
        $this->ch = curl_init();
    }

    public function withHeader(array $header): AIPicRequestAbstract {
        $this->header = $header;
        return $this;
    }

    public function withBody(array $body): AIPicRequestAbstract {
        $this->body = $body;
        return $this;
    }

    public function withPromptContext(string $promptContext): AIPicRequestAbstract {
        $this->promptContext = $promptContext;
        return $this;
    }

    public function withUrl(string $url): AIPicRequestAbstract {
        $this->url = $url;
        return $this;
    }

    public function withRequestPromptKey(string $requestPromptKey): AIPicRequestAbstract {
        $this->requestPromptKey = $requestPromptKey;
        return $this;
    }

    public function withResponseKey(string $responseKey): AIPicRequestAbstract {
        $this->responseKey = $responseKey;
        return $this;
    }

    public function withResponseSubkey(string $responseSubkey): AIPicRequestAbstract {
        $this->responseSubkey = $responseSubkey;
        return $this;
    }

    public function getDataArray(): array {
        $res = [];
        if(isset($this->response)) {
            $responseDecoded = $this->response ? json_decode($this->response, true): [];
            $res = $responseDecoded[$this->responseKey];
        }
        return $res;
    }

    public function getImagesUrlsArray(): array {
        $data = $this->getDataArray();
        $imagesUrls = [];
        if(isset($this->responseSubkey)) {
            foreach($data as $image) {
                $imagesUrls[] = $image[$this->responseSubkey];
            }
        } else {
            $imagesUrls[] = $data;
        }

        return $imagesUrls;
    }

    public function sendPrompt(string $prompt): bool|string {
        if(strlen($prompt) > 0) {
            $this->body[$this->requestPromptKey] = $this->promptContext. " " . $prompt;
            $bodyRequest = json_encode($this->getBody());

            curl_setopt($this->ch, CURLOPT_URL, $this->url);
            curl_setopt($this->ch, CURLOPT_POST, true);
            curl_setopt($this->ch, CURLOPT_POSTFIELDS, $bodyRequest);
            curl_setopt($this->ch, CURLOPT_HTTPHEADER, $this->header);
            curl_setopt($this->ch, CURLOPT_RETURNTRANSFER, true);
            $this->response = curl_exec($this->ch);
            return $this->response;
        }
        return false;
    }

    public function getHeader(): array {
        return $this->header;
    }

    public function getBody(): array {
        return $this->body;
    }

    public function getResponse(): string|bool|null {
        return $this->response;
    }

    public function getPromptContext(): string
    {
        return $this->promptContext;
    }

    public function getUrl(): string
    {
        return $this->url;
    }

    public function getRequestPromptKey(): string
    {
        return $this->requestPromptKey;
    }

    public function getResponseKey(): string
    {
        return $this->responseKey;
    }

    public function getResponseSubkey(): ?string
    {
        return $this->responseSubkey;
    }

    public static function getArrayFromString(string $txt): array {
        $dataLst = explode(",", $txt);
        $data = [];
        foreach($dataLst as $d) {
            if(str_contains($d, ":")) {
                $entries = explode(":", $d);
                $data[] = $entries[0] . ": " . $entries[1];
            }
        }
        return $data;
    }
}